### ISSUE TITLE
Bug: Connection refused by oauth proxy (port 3002) on loklak.org

### ISSUE THREAD

**Issue by sopu** [loklak/loklak_webclient#564] opened 2016-02-15 09:43 UTC
![screenshot from 2016-02-15 15 14 10](https://cloud.githubusercontent.com/assets/6399612/13044944/cbedf454-d3f6-11e5-88ae-2dc1a305f38d.png)

See this ^

**Comment by sudheesh001** [comment] 2016-02-15 12:07
Not able to reproduce. @aneeshd16 Can you check this please

**Comment by aneeshd16** [comment] 2016-02-15 12:11
@sopu Can happen if you are behind a firewall. Also try logging out and logging back in.

**Comment by sopu** [comment] 2016-02-15 12:15
@aneeshd16 thanx a lot :+1:

**Comment by aneeshd16** [comment] 2016-02-15 12:17
@sopu What worked? Were you behind a firewall or did you log out/in. Good to close this issue?

**Comment by sopu** [comment] 2016-02-15 12:18
Yes, I was behind a firewall! 
Closing...

**Comment by aneeshd16** [comment] 2016-02-15 17:45
I looked into the logs, there seems to be a problem with the response from loklak server. oauth-proxy is unable to parse the server's response. Will look into it.

**Comment by akigupta131** [comment] 2016-03-15 11:11
I am in the institute and proxy is there. Not working! Throws webpage not available.

**Comment by sudheesh001** [comment] 2016-03-28 06:18
@aneeshd16 Anything on this ?

**Comment by aneeshd16** [comment] 2016-03-28 06:37
I guess such type of proxies block connections on non-regular ports (ports apart from 80,443, etc). (Not sure about this). The only solution I see is to maybe map `loklak.net:3002` to something like `api.loklak.net`. Of course, this is a configuration issue, and can be fixed without any changes in the code.

**Closed** 2016-05-15 13:37 UTC
