### ISSUE TITLE
Bug shows post login screen even when not logged in

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#474] opened 2015-08-14 15:17 UTC
I couldn't reproduce this multiple times, but this screen shows up for a while before it moves to the home page with the search bar and then authenticates

<img width="1440" alt="screen shot 2015-08-14 at 8 45 41 pm" src="https://cloud.githubusercontent.com/assets/4545925/9277100/9fe5dd8a-42c5-11e5-8cf0-356a9a446724.png">

**Comment by fuksi** [comment] 2015-08-18 17:03
Can't reproduce this. The picture is above is also an old version. Home & Map are merged :) Please open this again if the bug occurs on live.

**Closed by fuksi** 2015-08-18 17:03 UTC
Labels: bug
