### ISSUE TITLE
Add a login via twitter button to the UI/UX targeting /auth/twitter on a Lightbox

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak_webclient#143] opened 2015-06-09 09:46 UTC

**Comment by mariobehling** [comment] 2015-06-09 17:55
Login via twitter can be done similar to Pinterest for example with a lightbox. On the right hand side, we are getting at the moment user "Alexander Pierce". Here should be a login button and as soon as logged in the name of the person that is logged in and next to it the picture.

**Comment by Orbiter** [comment] 2015-06-09 22:22
related to https://github.com/loklak/loklak_webclient/issues/138
I did not have seed this button yet. According to the issue-close-policy, someone else than you @sudheesh001 must close this issue after a review. From the front-ends which are running now, I cannot see this button and I am not able to see that this is working

**Comment by sudheesh001** [comment] 2015-06-10 05:10
Hi @Orbiter It was reviewed and merged by @aneeshd16 in d586e1f79b7760159252577c2ac1f1d479e2b9aa

I don't know why github closed it as me. Please check https://github.com/loklak/loklak_webclient/pull/147
![297376fe-0f0c-11e5-9282-1b691704f04f](https://cloud.githubusercontent.com/assets/4545925/8075354/28b055a6-0f5d-11e5-9af7-024ff2cbbbd4.png)

**Comment by mariobehling** [comment] 2015-06-10 06:15
Where can I test this? It would be good you update your the app on your server http://loklak.cloudapp.net:3001/

**Comment by Orbiter** [comment] 2015-06-10 06:39
I just tried this on http://loklak.cloudapp.net:3001 and I cannot push the button.
Furthermore, the font of the button is different *and* ugly. Why?

**Comment by aneeshd16** [comment] 2015-06-10 16:05
@Orbiter , fbf5033896e87be11253a205504560b99f5ab495 should fix it.
View it here http://aneesh-ojl02abl.cloudapp.net:3001/

**Comment by Orbiter** [comment] 2015-06-10 17:03
ok button works, but is this a Lightbox? I expected something that is 'floating' over loklak. The log-in you get here looks like you have left loklak and something is wrong.
Can you make this log-in floating?

**Comment by aneeshd16** [comment] 2015-06-11 03:00
Yep, @sudheesh001 is on it. I just fixed the button not getting clicked problem

**Comment by sudheesh001** [comment] 2015-06-13 08:32
@mariobehling @Orbiter Since the login is now happening through a click and the info being showed up in the nav bar do we still need this for the user as a lightbox ? The sessions are maintained even after the browser tab is closed and reopened at a later time.

I've rather pushed the tweet method to be onto a lightbox modal so that the user can post it from any page he's visiting in the application. The tweet functionality is yet to be merged with our hello.js implementation but UI/UX wise clicking the Tweet button gives you the action so that a tweet can be posted from anywhere.

http://loklak.cloudapp.net:3001/

**Comment by mariobehling** [comment] 2015-06-13 09:13
> Since the login is now happening through a click and the info being showed up in the nav bar do we still need this for the user as a lightbox ?

What is "this" exactly? If you talk about the interface, it is easier to understand screenshots/mockups.

Regarding the login, twitter is our first method, but it is best to follow the model of Pinterest. I already mentioned Pinterest a few times. Did you have a chance to try it out? Please login to Pinterest with FB and then see what is the following process. They will sign you up with an account etc.

**Comment by sudheesh001** [comment] 2015-06-13 09:17
@mariobehling Could you check this ? http://loklak.cloudapp.net:3001 the sign in is basically a click on the top navigation bar button which says Sign Up. Are we still going with this ? (This was updated to be this way after the integration of the new hello.js authentication system by @fuksi ) The angular bindings of the user information after login is available in the top nav, should the functionality of `Click to login` be changed ?

1. In case we use a lightbox like pintrest, should it appear on page load ?
2. What if a user dismisses the lightbox on page load, should there be another button in the top right corner asking to login, which would trigger the same lightbox ?

**Comment by mariobehling** [comment] 2015-06-13 09:26
@sudheesh001 Ok, how about this: We iterate. For now we keep it like that. Looks good to me. We need to discuss how we handle accounts and sign in through FB, G+ as well.

Regarding the start page, please compare this with twitter. Which is the relevant issue number here to discuss this? At the moment you post "your recent tweets" on the home screen, which is not the expected content. This should be the content at loklak.net/username.

**Comment by mariobehling** [comment] 2015-06-13 09:27
@sudheesh001 Also:
1. The sign in button does not change the display of the cursor when I go over the button. Please correct.
2. No need to display the username on the top .
(It is easy, just follow the design of twitter, please.)

**Comment by sudheesh001** [comment] 2015-06-13 10:06
> At the moment you post "your recent tweets" on the home screen, which is not the expected content. This should be the content at loklak.net/username.

Okay, After discussing with aneesh I had put it there because I didn't want the home page to look empty. It's great if the recent tweets go to `/username` as suggested.

**Comment by mariobehling** [comment] 2015-06-13 10:48
Common @sudheesh001. Please do not put the work you are expected to do on me. We discussed several times, that the expected behaviour in loklak is in most cases similar to twitter. 

> Does this mean that anyone can search for any username as /username ?

Could you check this out yourself how it is? E.g. check your own account: https://twitter.com/sudheesh001

How does this work for anonymous and logged in users? We expect the same behaviour in loklak.

Could you help us please and check out these questions yourself in future and post the solution that twitter offers in issues yourself here?

**Comment by sudheesh001** [comment] 2015-06-14 03:21
Dependant on https://github.com/loklak/loklak_webclient/issues/119

**Comment by aneeshd16** [comment] 2015-06-14 16:35
Closed via #179

**Closed by aneeshd16** 2015-06-14 16:35 UTC
Labels: Authentication, Design, enhancement, Loklak Tweets, Priority 1 - High
