### ISSUE TITLE
Map not showing up regularly when clicking around in loklak

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#497] opened 2015-08-19 11:34 UTC
After being logged in users goes back to "home page". Here the map regularly does not show up. It works sometimes, if the user refreshes.

![screenshot from 2015-08-19 13 33 34](https://cloud.githubusercontent.com/assets/1583873/9355191/064a1884-4677-11e5-92d3-24e46c675e9c.png)

**Comment by fuksi** [comment] 2015-08-20 22:51
I can't reproduce this, but this is my analysis of the error from what I see: if you can't see the map, chances are, in that session (until refreshed), you won't be able to see `Followers`, `Followers` on `Timeline` view, and you won't be able to do a search either

Reason: you are blocked from loklak server for a short period of time, and all of the data mentioned above are from loklak server. I can't investiage more at the moment because the loklak.net server is quite unstable at the moment.

@sudheesh001, @aneeshd16, @prasht63 have you guys been expericencing this? Can you take a screenshot of the network traffic in dev console if it happens? Thanks!

**Comment by sudheesh001** [comment] 2015-08-21 05:38
@fuksi Unable to reproduce, the map seems to load correctly. But another problem I noticed is that the map seems to pushed to a zoom level 2 and slightly off the center on retina displays. Looks centered on non retina displays.

**Comment by mariobehling** [comment] 2015-08-21 05:43
@sudheesh001 Screenshot?

**Comment by fuksi** [comment] 2015-08-28 13:45
I still can't reproduce this by click around, log in/out/in/out
Also recently the source for markers in Map view is changed to loklak (previously is twitter api), so there is even less chance this error could happen. Let's close this!

**Closed by fuksi** 2015-08-28 13:45 UTC
Labels: bug, Design, Loklak Map - Prashant, Search - Fuksi
