### ISSUE TITLE
Implement data from Freifunk router network

### ISSUE THREAD

**Issue by zyzo** [loklak/loklak_webclient#324] opened 2015-07-09 09:50 UTC
Freifunk network map : http://www.freifunk-karte.de/

Map repo : https://github.com/ffansbach/de-map

This map currently gets data from freifunk api data https://raw.githubusercontent.com/freifunk/directory.api.freifunk.net/master/directory.json. In each community json file, there is `node` and `nodeMaps` fields, which in turn contain information about community router nodes.

An example of router list : 
https://netmon.freifunk-ansbach.de/routerlist.php

The first step is to push this data into loklak, and visualize it on loklak map.

Then, loklak can implement automatic tweets service, that tweet when a router node change status, for example. But right now we focus on the first step.

**Comment by zyzo** [comment] 2015-07-11 05:43
Actually, this task is decomposed into four different tasks, as sources are in 4 different data formats. Some of them are known formats to represent wifi routers that are used anywhere, not just at freifunk : 

1- **openwifimap** http://openwifimap.net/ 

Examples : 
* http://api.openwifimap.net/view_nodes
* http://mapapi.weimarnetz.de/view_nodes

2- **netmon** http://netmon.ca/ 

Examples : 
* https://netmon.freifunk-franken.de/api/rest/api.php?rquest=routerlist
* https://netmon.freifunk-emskirchen.de/api/rest/api.php?rquest=routerlist
* https://netmon.freifunk-neuendettelsau.de/api/rest/api.php?rquest=routerlist

3- **nodelist**
* http://map.freifunk-ruhrgebiet.de/nodes.json
* http://nodeapi.vfn-nrw.de/index.php/get/nodes/community/3/format/nodelist

4- **freifunk custom type**
* https://saar.freifunk.net/map/nodes.json
* http://map.freifunk-ruhrgebiet.de/nodes.json

**Comment by zyzo** [comment] 2015-07-13 16:23
I'm looking for schemas of these sources. This is where I've gotten so far

* openwifimap doesn't seem to have a json schema : https://github.com/mnin/freifunk_ios/issues/14. However the data format is well documented here https://github.com/freifunk/openwifimap-api.

* netmon is in xml format ! The simplest solution is to consider this a corner case and do not validate xml at all. I don't think a lot of services use this old format anymore.

* nodelist schema : https://github.com/ffansbach/de-map/blob/master/schema/nodelist-schema-1.0.1.json  , although it doesn't really correspond to the examples. @andibraeu is it the right schema for nodelist ?

**Comment by zyzo** [comment] 2015-07-14 04:56
Another free wifi network http://map.ninux.org

The integration of ninux is promising since their api is in geojson, and we already have a geojson push service : 

nodes: https://ninux.nodeshot.org/api/v1/nodes.geojson?format=json
links: https://ninux.nodeshot.org/api/v1/links.geojson?format=json

**Comment by zyzo** [comment] 2015-07-15 06:00
Data from ninux can be simply added using this link : 
http://localhost:9000/api/push/geojson.json?url=https://ninux.nodeshot.org/api/v1/nodes.geojson?format=json&source_type=NINUX&map_type=name:screen_name&user:user.screen_name&user:user.name&details:link.

(Althoug this request currently failed because `mtime` field is missing. Will be fixed with strategy discussed in https://github.com/loklak/loklak_server/pull/77#issuecomment-121219647)

**Comment by zyzo** [comment] 2015-07-16 07:25
Helper script to import (all) freifunk data into loklak : https://github.com/zyzo/ff2ll

**Comment by zyzo** [comment] 2015-07-17 04:40
http://localhost:9000/api/push/geojson.json?url=https://ninux.nodeshot.org/api/v1/nodes.geojson?format=json&source_type=NINUX&map_type=name:screen_name,user:user.screen_name,user:user.name,details:link,description:text,updated:mtime

**Comment by mariobehling** [comment] 2015-07-17 06:05
In your standup you wrote:

> The messages imported from freifunk loklak_webclient #324 are saved into elastic and have location_point field. But on client app I can't visualize them on the map. They are listed in the live tab however. 

What search will give me results to see freifunk nodes info?

**Comment by zyzo** [comment] 2015-07-17 07:13
@mariobehling This info is available on local environment only, as freifunk routers branches are not merged into master (a PR will be opened after https://github.com/loklak/loklak_server/pull/77 is merged). 

Steps to reproduce the bug on local environment : 
1. Compile & run loklak_server, branch wifi-routers-push-service
2. Clone repo https://github.com/zyzo/ff2ll, and run importer script : `php import2loklak.php` (might take a while)
3. Run loklak_webclient, and go to this url (which performs a search by source type) : `http://localhost:3000/search?q=%2Fsource_type%3DFREIFUNK_NODE%2B%2Fmap`

**Comment by mariobehling** [comment] 2015-07-17 08:34
@zyzo Do you have a server where you could set up loklak and we can test it there, if we have feedback. It is not possible to deploy all branches of different developers and test it.

**Comment by zyzo** [comment] 2015-07-21 06:33
After analysis, the problem is found (!). When searching things on map view, the location constraint is present in search query, and the server side will only searches for messages with `place_context=from` ([code](https://github.com/loklak/loklak_server/blob/master/src/org/loklak/data/QueryEntry.java#L628)). So the messages with `place_context=about` are not returned. (however when creating new messages the default value is `about` ([code](https://github.com/loklak/loklak_server/blob/master/src/org/loklak/data/MessageEntry.java#L436)).

This situation doesn't fit in current set up when map only displays `from` messages by default. The imported messages are really `about` messages since they are description of the place (wifi router, community), but we want to display them at that place on the map. The fix is simple : add `/about` constraint to the search query.

Screenshots :

without /about : 
![screenshot from 2015-07-21 13 28 58](https://cloud.githubusercontent.com/assets/6483446/8794324/c3ec9dee-2fac-11e5-811c-d4b007387c71.png)
 
with about : 
![screenshot from 2015-07-21 13 29 34](https://cloud.githubusercontent.com/assets/6483446/8794325/c8681376-2fac-11e5-81fd-62db4874b0cf.png)

(unable to reproduce this in test env due to painful heroku app memory restriction)

The location of western fossasia communities seem wrong. That would be subject for another issue.

**Comment by mariobehling** [comment] 2015-07-21 09:07
This is confusing. The issue is about Freifunk routers - actual devices. It is not directly related to communities.

**Comment by zyzo** [comment] 2015-07-21 12:42
@mariobehling  the screenshots are just for demo purpose. The bug analysis applies for all cases, when data are imported into the backend : Freifunk routers AND Fossasia communities & other things as well.

**Comment by zyzo** [comment] 2015-07-21 12:50
as of why the demo do not show freifunk data, it's only because the freifunk router feature and search by source_type feature are on parallel branch. But it doesn't matter as the issue affects all cases.

**Comment by mariobehling** [comment] 2015-07-21 13:02
@zyzo This is confusing. There is an issue here, that is related to the Freifunk/FOSSASIA API https://github.com/loklak/loklak_webclient/issues/206 You could also add another issue that focuses on the API. 

Please do not mix different topics. This issue specifically relates to the router network. We should put things where they belong. Please separate the issues.

**Comment by zyzo** [comment] 2015-07-31 06:22
This issue is implemented in the context of https://github.com/loklak/loklak_server/issues/84 & can be tested at http://loklak-client.danghaian.com/addConnection. Closing issue.

**Comment by mariobehling** [comment] 2015-07-31 06:42
Update Frequency and Lifetime choices do not make sense ![screenshot from 2015-07-31 08 41 20](https://cloud.githubusercontent.com/assets/1583873/9002077/03e98122-3760-11e5-9c2a-c4f12c0d38ac.png)

**Comment by mariobehling** [comment] 2015-07-31 06:46
Please check if you can get some inspiration from twitterfeed.com for example.

![screenshot from 2015-07-31 08 45 40](https://cloud.githubusercontent.com/assets/1583873/9002145/97efb562-3760-11e5-8de9-32a1f232a3bc.png)

**Comment by zyzo** [comment] 2015-07-31 16:01
Thanks for the reference. It surely makes sense to set some fixed values for update frequency. About lifetime, I don't really understand the use case. @Orbiter could you provide some inputs so I can finely tune implementation of lifetime field ? 

Another interesting thing is the test button to validate the url. As validation using json schema is already there this feature should cause no challenge.

**Comment by mariobehling** [comment] 2016-05-13 16:58
Closing it due to changed priorities.

**Closed by mariobehling** 2016-05-13 16:58 UTC
Labels: IoT, Loklak Map
