### ISSUE TITLE
Report: Data incorrectly displayed and evaluated

### ISSUE THREAD

**Issue by mariobehling** [loklak/loklak_webclient#508] opened 2015-08-20 19:49 UTC
* [x] Country data shows up in city table
* [ ] countries and cities that are same, e.g. Singapore show different numbers in country and city table
* [ ] City locations like "Phnom Penh, Cambodia" and "Phnom Penh" should show up as one location
![screenshot from 2015-08-20 21 47 13](https://cloud.githubusercontent.com/assets/1583873/9393887/20353fa8-4785-11e5-98d0-ef0f64a22d4d.png)

* [ ] numbers - looks like lots are missing
![screenshot from 2015-08-20 22 02 40](https://cloud.githubusercontent.com/assets/1583873/9394235/a4ff779c-4787-11e5-91d4-682e75931fd3.png)

**Comment by prasht63** [comment] 2015-08-21 19:18
@mariobehling For this @Orbiter will have to add a generic name for every city.Since many people have added "Berlin" , "Berlin,Germany" , "Berlin,Europe" so all these get classified differently.I am proposing that while storing the followers data in Loklak a generic place name field to be added in the response which will map all variants of one city to its name and that shall be used.

For Singapore, I think SIngapore is also a city so that's not an error.

**Comment by mariobehling** [comment] 2015-08-21 21:14
@prasht63 Good approach. Please create an issue for this.

**Comment by prasht63** [comment] 2015-08-22 08:13
Issue created here https://github.com/loklak/loklak_server/issues/118

**Comment by Orbiter** [comment] 2015-10-14 16:44
The "Singapore" question is not an error. Consider that some people give the location "Singapore, Chinatown", then this does not show up in the statistic and creates the glitch. But this cannot be corrected easily. If in another example someone would haven given "Singapore, Singapore" (i.e. "City, Country"), then this problem would be corrected with https://github.com/loklak/loklak_server/issues/118.
I suggest to leave it that way since the "Singapore"-Bug is not a bug and will be slightly corrected with https://github.com/loklak/loklak_server/issues/118
That means we can close this now.

**Closed by Orbiter** 2015-10-14 16:44 UTC
Labels: bug, IoT - Prashant
